# Generated by Django 5.2 on 2025-05-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='qr_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
